MODEL = 'model'
VARIANCE = 'variance'
NOISE = 'noise'
OPTIMIZATION = 'optimization'
RESTARTS = 'restarts'
LOW = 'low'
HIGH = 'high'
FIDELITY = 'fidelity'
COST = 'cost'
NUM_ITER = 'num_iter'
NUM_FIDELITIES = 'num_fidelities'

# Kernels
MATERN = 'matern'
RBF = 'rbf'
WHITE = 'white'
PERIODIC = 'periodic'
SEPARATOR = '_'

# Kernel hyperparameter names
LENGTHSCALE = 'lengthscale'
PERIOD = 'period'
MATERN_LENGTHSCALE = MATERN + SEPARATOR + LENGTHSCALE
MATERN_VARIANCE = MATERN + SEPARATOR + VARIANCE
RBF_LENGTHSCALE = RBF + SEPARATOR + LENGTHSCALE
RBF_VARIANCE = RBF + SEPARATOR + VARIANCE
WHITE_LENGTHSCALE = WHITE + SEPARATOR + LENGTHSCALE
WHITE_VARIANCE = WHITE + SEPARATOR + VARIANCE
PERIODIC_LENGTHSCALE = PERIODIC + SEPARATOR + LENGTHSCALE
PERIODIC_PERIOD = PERIODIC + SEPARATOR + PERIOD
PERIODIC_VARIANCE = PERIODIC + SEPARATOR + VARIANCE

# Model hyperparameter names
MODEL_NOISE_VARIANCE = MODEL + SEPARATOR + NOISE + SEPARATOR + VARIANCE
OPTIMIZATION_RESTARTS = OPTIMIZATION + SEPARATOR + RESTARTS
LOW_FIDELITY_COST = LOW + SEPARATOR + FIDELITY + SEPARATOR + COST
HIGH_FIDELITY_COST = HIGH + SEPARATOR + FIDELITY + SEPARATOR + COST
OPTIMIZER_UPDATE_INTERVAL = 'optimizer_update_interval'
