# General terminologiy:
MODEL = 'model'
VARIANCE = 'variance'
NOISE = 'noise'
OPTIMIZATION = 'optimization'
RESTARTS = 'restarts'
LOW = 'low'
HIGH = 'high'
FIDELITY = 'fidelity'
COST = 'cost'
NUM_ITER = 'num_iter'
NUM_FIDELITIES = 'num_fidelities'
PRODUCT = 'product'
SUM = 'sum'

# Misc
MATPLOTLIB_BACKEND = 'matplotlib_backend'
SEPARATOR = '_'

# Kernels
KERNELS = 'kernels'
KERNELS_LOW = KERNELS + SEPARATOR + LOW
SDE = 'sde'
MATERN32 = 'Matern32'
MATERN52 = 'Matern52'
RBF = 'rbf'
WHITE = 'white'
PERIODIC = 'periodic'
EXPONENTIAL = 'exponential'
BIAS = 'bias'
POSSIBLE_KERNELS = [MATERN32, RBF, WHITE, PERIODIC, EXPONENTIAL, SDE+SEPARATOR+MATERN32, SDE+SEPARATOR+RBF, SDE+SEPARATOR+WHITE, SDE+SEPARATOR+PERIODIC, SDE+SEPARATOR+EXPONENTIAL]
KERNEL_COMBINATION = 'kernel_combination'

# Kernel hyperparameter names
LENGTHSCALE = 'lengthscale'
PERIOD = 'period'
MATERN32_LENGTHSCALE = MATERN32 + SEPARATOR + LENGTHSCALE
MATERN32_VARIANCE = MATERN32 + SEPARATOR + VARIANCE
RBF_LENGTHSCALE = RBF + SEPARATOR + LENGTHSCALE
RBF_VARIANCE = RBF + SEPARATOR + VARIANCE
WHITE_LENGTHSCALE = WHITE + SEPARATOR + LENGTHSCALE
WHITE_VARIANCE = WHITE + SEPARATOR + VARIANCE
PERIODIC_LENGTHSCALE = PERIODIC + SEPARATOR + LENGTHSCALE
PERIODIC_PERIOD = PERIODIC + SEPARATOR + PERIOD
PERIODIC_VARIANCE = PERIODIC + SEPARATOR + VARIANCE
# NOTE: We use the original names above as HIGH fidelity hyperparameters.
# NOTE: The following are not used in the code, but are here for completeness.
# MATERN32_LENGTHSCALE_HIGH = MATERN32_LENGTHSCALE + SEPARATOR + HIGH
# MATERN32_VARIANCE_HIGH = MATERN32_VARIANCE + SEPARATOR + HIGH
# RBF_LENGTHSCALE_HIGH = RBF_LENGTHSCALE + SEPARATOR + HIGH
# RBF_VARIANCE_HIGH = RBF_VARIANCE + SEPARATOR + HIGH
# WHITE_LENGTHSCALE_HIGH = WHITE_LENGTHSCALE + SEPARATOR + HIGH
# WHITE_VARIANCE_HIGH = WHITE_VARIANCE + SEPARATOR + HIGH
# PERIODIC_LENGTHSCALE_HIGH = PERIODIC_LENGTHSCALE + SEPARATOR + HIGH
# PERIODIC_PERIOD_HIGH = PERIODIC_PERIOD + SEPARATOR + HIGH
# PERIODIC_VARIANCE_HIGH = PERIODIC_VARIANCE + SEPARATOR + HIGH
MATERN32_LENGTHSCALE_LOW = MATERN32_LENGTHSCALE + SEPARATOR + LOW
MATERN32_VARIANCE_LOW = MATERN32_VARIANCE + SEPARATOR + LOW
RBF_LENGTHSCALE_LOW = RBF_LENGTHSCALE + SEPARATOR + LOW
RBF_VARIANCE_LOW = RBF_VARIANCE + SEPARATOR + LOW
WHITE_LENGTHSCALE_LOW = WHITE_LENGTHSCALE + SEPARATOR + LOW
WHITE_VARIANCE_LOW = WHITE_VARIANCE + SEPARATOR + LOW
PERIODIC_LENGTHSCALE_LOW = PERIODIC_LENGTHSCALE + SEPARATOR + LOW
PERIODIC_PERIOD_LOW = PERIODIC_PERIOD + SEPARATOR + LOW
PERIODIC_VARIANCE_LOW = PERIODIC_VARIANCE + SEPARATOR + LOW


# Model hyperparameter names
MODEL_NOISE_VARIANCE = MODEL + SEPARATOR + NOISE + SEPARATOR + VARIANCE
OPTIMIZATION_RESTARTS = OPTIMIZATION + SEPARATOR + RESTARTS
LOW_FIDELITY_COST = LOW + SEPARATOR + FIDELITY + SEPARATOR + COST
HIGH_FIDELITY_COST = HIGH + SEPARATOR + FIDELITY + SEPARATOR + COST
OPTIMIZER_UPDATE_INTERVAL = 'optimizer_update_interval'
