# Misc
MATPLOTLIB_BACKEND = 'matplotlib_backend'
SEPARATOR = '_'

# General terminologiy:
MODEL = 'model'
VARIANCE = 'variance'
NOISE = 'noise'
OPTIMIZATION = 'optimization'
RESTARTS = 'restarts'
LOW = 'low'
HIGH = 'high'
FIDELITY = 'fidelity'
COST = 'cost'
MAX_COST = 'max' + SEPARATOR + COST
NUM_ITER = 'num_iter'
NUM_FIDELITIES = 'num_fidelities'
PRODUCT = 'product'
SUM = 'sum'
NP_SEED = 'np_seed'

# Kernels
KERNELS = 'kernels'
KERNELS_LOW = KERNELS + SEPARATOR + LOW
KERNELS_HIGH = KERNELS + SEPARATOR + HIGH
WATER = 'water'
KERNELS_HIGH_WATER = KERNELS + SEPARATOR + HIGH + SEPARATOR + WATER
KERNELS_LOW_WATER = KERNELS + SEPARATOR + LOW + SEPARATOR + WATER
SDE = 'sde'
MATERN32 = 'Matern32'
MATERN52 = 'Matern52'
RBF = 'rbf'
WHITE = 'white'
PERIODIC = 'periodic'
EXPONENTIAL = 'exponential'
BIAS = 'bias'
POSSIBLE_KERNELS = [MATERN32, RBF, WHITE, PERIODIC, EXPONENTIAL, SDE+SEPARATOR+MATERN32, SDE+SEPARATOR+RBF, SDE+SEPARATOR+WHITE, SDE+SEPARATOR+PERIODIC, SDE+SEPARATOR+EXPONENTIAL]
KERNEL_COMBINATION = 'kernel_combination'

# Kernel hyperparameter names
LENGTHSCALE = 'lengthscale'
PERIOD = 'period'
MATERN32_LENGTHSCALE = MATERN32 + SEPARATOR + LENGTHSCALE
MATERN32_VARIANCE = MATERN32 + SEPARATOR + VARIANCE
MATERN52_LENGTHSCALE = MATERN52 + SEPARATOR + LENGTHSCALE
MATERN52_VARIANCE = MATERN52 + SEPARATOR + VARIANCE
RBF_LENGTHSCALE = RBF + SEPARATOR + LENGTHSCALE
RBF_VARIANCE = RBF + SEPARATOR + VARIANCE
WHITE_LENGTHSCALE = WHITE + SEPARATOR + LENGTHSCALE
WHITE_VARIANCE = WHITE + SEPARATOR + VARIANCE
PERIODIC_LENGTHSCALE = PERIODIC + SEPARATOR + LENGTHSCALE
PERIODIC_PERIOD = PERIODIC + SEPARATOR + PERIOD
PERIODIC_VARIANCE = PERIODIC + SEPARATOR + VARIANCE
MATERN32_LENGTHSCALE_LOW = MATERN32_LENGTHSCALE + SEPARATOR + LOW
MATERN32_VARIANCE_LOW = MATERN32_VARIANCE + SEPARATOR + LOW
MATERN52_LENGTHSCALE_LOW = MATERN52_LENGTHSCALE + SEPARATOR + LOW
MATERN52_VARIANCE_LOW = MATERN52_VARIANCE + SEPARATOR + LOW
RBF_LENGTHSCALE_LOW = RBF_LENGTHSCALE + SEPARATOR + LOW
RBF_VARIANCE_LOW = RBF_VARIANCE + SEPARATOR + LOW
WHITE_LENGTHSCALE_LOW = WHITE_LENGTHSCALE + SEPARATOR + LOW
WHITE_VARIANCE_LOW = WHITE_VARIANCE + SEPARATOR + LOW
PERIODIC_LENGTHSCALE_LOW = PERIODIC_LENGTHSCALE + SEPARATOR + LOW
PERIODIC_PERIOD_LOW = PERIODIC_PERIOD + SEPARATOR + LOW
PERIODIC_VARIANCE_LOW = PERIODIC_VARIANCE + SEPARATOR + LOW
# NOTE: We use the original names above as HIGH fidelity hyperparameters, so that we can switch to single fidelity
# NOTE: The following are not used in the code, but are here for completeness.
# MATERN32_LENGTHSCALE_HIGH = MATERN32_LENGTHSCALE + SEPARATOR + HIGH
# MATERN32_VARIANCE_HIGH = MATERN32_VARIANCE + SEPARATOR + HIGH
# RBF_LENGTHSCALE_HIGH = RBF_LENGTHSCALE + SEPARATOR + HIGH
# RBF_VARIANCE_HIGH = RBF_VARIANCE + SEPARATOR + HIGH
# WHITE_LENGTHSCALE_HIGH = WHITE_LENGTHSCALE + SEPARATOR + HIGH
# WHITE_VARIANCE_HIGH = WHITE_VARIANCE + SEPARATOR + HIGH
# PERIODIC_LENGTHSCALE_HIGH = PERIODIC_LENGTHSCALE + SEPARATOR + HIGH
# PERIODIC_PERIOD_HIGH = PERIODIC_PERIOD + SEPARATOR + HIGH
# PERIODIC_VARIANCE_HIGH = PERIODIC_VARIANCE + SEPARATOR + HIGH

# special kernel identifyings for water, same pattern as above
MATERN32_LENGTHSCALE_HIGH_WATER = MATERN32_LENGTHSCALE + SEPARATOR + HIGH + SEPARATOR + WATER
MATERN32_VARIANCE_HIGH_WATER = MATERN32_VARIANCE + SEPARATOR + HIGH + SEPARATOR + WATER
MATERN52_LENGTHSCALE_HIGH_WATER = MATERN52_LENGTHSCALE + SEPARATOR + HIGH + SEPARATOR + WATER
MATERN52_VARIANCE_HIGH_WATER = MATERN52_VARIANCE + SEPARATOR + HIGH + SEPARATOR + WATER
RBF_LENGTHSCALE_HIGH_WATER = RBF_LENGTHSCALE + SEPARATOR + HIGH + SEPARATOR + WATER
RBF_VARIANCE_HIGH_WATER = RBF_VARIANCE + SEPARATOR + HIGH + SEPARATOR + WATER
WHITE_LENGTHSCALE_HIGH_WATER = WHITE_LENGTHSCALE + SEPARATOR + HIGH + SEPARATOR + WATER
WHITE_VARIANCE_HIGH_WATER = WHITE_VARIANCE + SEPARATOR + HIGH + SEPARATOR + WATER
PERIODIC_LENGTHSCALE_HIGH_WATER = PERIODIC_LENGTHSCALE + SEPARATOR + HIGH + SEPARATOR + WATER
PERIODIC_PERIOD_HIGH_WATER = PERIODIC_PERIOD + SEPARATOR + HIGH + SEPARATOR + WATER
PERIODIC_VARIANCE_HIGH_WATER = PERIODIC_VARIANCE + SEPARATOR + HIGH + SEPARATOR + WATER
MATERN32_LENGTHSCALE_LOW_WATER = MATERN32_LENGTHSCALE + SEPARATOR + LOW + SEPARATOR + WATER
MATERN32_VARIANCE_LOW_WATER = MATERN32_VARIANCE + SEPARATOR + LOW + SEPARATOR + WATER
MATERN52_LENGTHSCALE_LOW_WATER = MATERN52_LENGTHSCALE + SEPARATOR + LOW + SEPARATOR + WATER
MATERN52_VARIANCE_LOW_WATER = MATERN52_VARIANCE + SEPARATOR + LOW + SEPARATOR + WATER
RBF_LENGTHSCALE_LOW_WATER = RBF_LENGTHSCALE + SEPARATOR + LOW + SEPARATOR + WATER
RBF_VARIANCE_LOW_WATER = RBF_VARIANCE + SEPARATOR + LOW + SEPARATOR + WATER
WHITE_LENGTHSCALE_LOW_WATER = WHITE_LENGTHSCALE + SEPARATOR + LOW + SEPARATOR + WATER
WHITE_VARIANCE_LOW_WATER = WHITE_VARIANCE + SEPARATOR + LOW + SEPARATOR + WATER
PERIODIC_LENGTHSCALE_LOW_WATER = PERIODIC_LENGTHSCALE + SEPARATOR + LOW + SEPARATOR + WATER
PERIODIC_PERIOD_LOW_WATER = PERIODIC_PERIOD + SEPARATOR + LOW + SEPARATOR + WATER
PERIODIC_VARIANCE_LOW_WATER = PERIODIC_VARIANCE + SEPARATOR + LOW + SEPARATOR + WATER


# Model hyperparameter names
MODEL_NOISE_VARIANCE = MODEL + SEPARATOR + NOISE + SEPARATOR + VARIANCE
MIXED_NOISE_LOW = "mixed" + SEPARATOR + NOISE + SEPARATOR + LOW
MIXED_NOISE_HIGH = "mixed" + SEPARATOR + NOISE + SEPARATOR + HIGH
OPTIMIZATION_RESTARTS = OPTIMIZATION + SEPARATOR + RESTARTS
LOW_FIDELITY_COST = LOW + SEPARATOR + FIDELITY + SEPARATOR + COST
HIGH_FIDELITY_COST = HIGH + SEPARATOR + FIDELITY + SEPARATOR + COST
OPTIMIZER_UPDATE_INTERVAL = 'optimizer_update_interval'
